# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 06:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=2000, null=True)),
                ('long_description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('INT', 'Integer'), ('STR', 'String'), ('FLT', 'Float'), ('FLE', 'File'), ('SCT', 'Select'), ('RDO', 'Radio'), ('CHK', 'Checkbox')], max_length=3)),
                ('required', models.BooleanField()),
                ('help', models.CharField(blank=True, max_length=300, null=True)),
                ('display_order', models.IntegerField()),
                ('default_value', models.CharField(blank=True, max_length=300, null=True)),
                ('min_value', models.FloatField(null=True)),
                ('max_value', models.FloatField(null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Package')),
                ('parent_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_option', to='website.Option')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('argument_hash', models.BinaryField(db_index=True)),
                ('queue_time', models.DateTimeField(null=True)),
                ('run_start_time', models.DateTimeField(null=True)),
                ('run_end_time', models.DateTimeField(null=True)),
                ('error', models.NullBooleanField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Package')),
            ],
        ),
        migrations.CreateModel(
            name='RunArgument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=300, null=True)),
                ('file_hash', models.BinaryField()),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Parameter')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Run')),
            ],
        ),
        migrations.CreateModel(
            name='RunFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.BinaryField(db_index=True, unique=True)),
                ('file', models.FileField(upload_to=website.models.run_file_path)),
                ('size', models.IntegerField()),
                ('mime_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RunFileAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=300)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Run')),
                ('run_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.RunFile')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Parameter'),
        ),
    ]
