# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170123_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='parent_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_option', to='website.Option'),
        ),
    ]
