# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170130_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='label',
            field=models.CharField(default='pancakes', max_length=100),
            preserve_default=False,
        ),
    ]
