# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_parameter_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
