# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170130_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
