# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_option_is_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='parameter',
            name='step_value',
            field=models.FloatField(null=True),
        ),
    ]
