# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20170203_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameter',
            name='file_accept',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
